import icons from "../icons";

export default {
  details: {
    name: "Sidhanth Rathod",
    about:
      "Self-taught Front-End Web Developer passionate about creating beautiful and performant websites, aiming to create the best user experience possible! Everything I make is beautiful. I use Arch btw.",
    email: "siduck@tutanota.com",
    phone: "+91 9701611257",
    location: "Hyderabad, India",
    role:'Frontend Developer',
    // website: "https://github.com/siduck",

    github: "siduck",
    linkedin: "https://www.linkedin.com/in/sidhanth-rathod-b3829a263",
  },

  workExp: [
    {
      company: "Jamesmccallumconsulting (Freelance)",
      title: "React Developer",
      date: "2022 Oct - 2023 Jan",
      desc: [
        "- Converted UI figma designs into responsive React + Tailwindcss components",
        "- Created responsive landing pages and a github profile dashboard using github search api",
      ].join("\n"),
    },
    {
      company: "Ideanomic",
      title: "Frontend Developer",
      date: "2023 April - 2025 May",
      desc: [
        "- Responsible for creating and maintaining company's website",
        "- Converted UI figma designs into real responsive React + Unocss components",
        "- Used Git for version control system for managing various branches for deployment & integrated with vercel deployments",
        "- Used React and Nextjs to build a fully functional H.R platform, integrated API into the frontend to show user data and maintained four various deployments.",
      ].join("\n"),
    },
  ],

  education: [
    {
      institution: "Sarada College",
      date: "2019 – 2022",
      qualification: "BHMCT ( discontinued )",
    },
    {
      institution: "Chaitanya College",
      date: "2017 – 2019",
      qualification: "Intermediate education",
    },
  ],

  projects: [
    {
      name: "Quick CV",
      link: "https://github.com/siduck/quickcv",
      desc: "Fast resume / cv builder for making beautiful resumes & supports exporting to high quality pdfs using native print(). This resume is generated by quickcv web app",
    },
    {
      name: "NvChad",
      link: "https://github.com/nvchad/nvchad",
      desc: `Blazing fast Neovim config framework providing solid defaults, beautiful UI and a set of exclusive plugins built for it. Enabling users to create their own IDE experiences within Neovim! Most`,
    },
    {
      name: "Volt",
      link: "https://github.com/nvzone/volt",
      desc: "UI framework for drawing reactive & interactive interfaces within Neovim text editor.",
    },

    {
      name: "Typr",
      link: "https://github.com/nvzone/typr",
      desc: "Most beautiful terminal typing practice plugin with fancy stats dashboard within Neovim made using Volt.",
    },

    {
      name: "Minty",
      link: "https://github.com/nvzone/minty",
      desc: "Color manipulation popup ui within terminal for Neovim, like never before!",
    },
  ],

  skills: [
    { name: "Html", icon: icons.html },
    { name: "Css", icon: icons.css },
    { name: "JavaScript", icon: icons.javascript },
    { name: "TypeScript", icon: icons.typescript },
    { name: "Svelte", icon: icons.svelte },
    { name: "SolidJS", icon: icons.solidjs },
    { name: "React", icon: icons.react },
    { name: "Lua", icon: icons.lua },
    { name: "Tailwind", icon: icons.tailwind },
    { name: "UnoCSS", icon: icons.unocss },
  ],
};
